### ISSUE TITLE
Simple custom toolbar

### ISSUE THREAD

**Issue by philtr** [ovenbits-ingredients/fondant#14]
Allow the user to pass in an array of toolbar options and only create buttons for those specifically.

``` javascript
$(thing).fondant({
  toolbar: true,
  buttons: [ "b", "i", "ol", "ul", "indent", "outdent", "clear" ]
});
```

**Comment by jdtornow** [comment]
Great idea. :thumbsup: 

Would also be nice to document the list of possible buttons in the readme somewhere while we're at it.

**Comment by philtr** [comment]
Done. (e8e0fa90b2d61733d28a055d3a480c5053b1a768)
